   const CONFIG = {
    introTitle: 'BÃ¹i Thá»‹ NhÃ n',
    introDesc: `Anh Tháº­t Sá»± Xin Lá»—i Em VÃ¬ Chuyá»‡n Vá»«a Qua :(`,
    btnIntro: 'Cáº£ NgÃ y HÃ´m Nay ÄÃ£ Suy NghÄ© VÃ  TrÃ¡ch Báº£n ThÃ¢n Ráº¥t Nhiá»u :'(',
    title: 'Tháº­t Sá»± Anh KhÃ´ng Muá»‘n ChÃºng Ta NhÆ° NÃ y! Tháº­t Äáº¥y ',
    desc: 'Anh Xin Em HÃ£y Bá» Qua VÃ  Cháº¥p Nháº­n Lá»i Xin Lá»—i Cá»§a Anh Äá»ƒ Anh CÃ³ Thá»ƒ Sá»­a Sai VÃ  Quan TÃ¢m Em HÆ¡n.',
    btnYes: 'ChÃ­nh Em ÄÃ£ LÃ m Cho Báº£n THÃ¢n Anh THay Äá»•i Nhiá»u HÆ¡n Tá»« Khi CÃ³ Em',
    btnNo: 'NÃ³ NhÆ° 1 Pháº§n Cuá»™c Sá»‘ng Cá»§a ANh Hiá»‡n Táº¡i Váº­y !! Nhá»¯ng HÃ¬nh áº¢nh vÃ  Tin Nháº¯n NÃ³ NhÆ° Tiáº¿p THÃªm Äá»™ng Lá»±c Äá»ƒ Anh Cá»‘ Gáº¯ng Váº­y <3',
    question :'Anh Ráº¥t Xin Lá»—i VÃ  Em CÃ³ Thá»ƒ Cho Anh 1 CÆ¡ Há»™i Cuá»‘i CÃ¹ng Äá»ƒ Nhá»¯ng Lá»i NÃ³i MÃ¬nh NÃ³i Vá»›i Nhau Äá»ƒ Anh CÃ³ Thá»ƒ Thá»±c Hiá»‡n ÄÆ°á»£c!!',
    btnReply: 'Anh Xin Lá»—i !!! Tháº­t LÃ²ng Xin Lá»—i -> BÃ™I THá»Š NHÃ€N <3',
    reply: 'Anh Xin Lá»—i VÃ¬ Táº¥t Cáº£!!,
    mess: 'Anh biáº¿t mÃ  ğŸ¥°. YÃªu em nhiá»u nhiá»u ğŸ˜˜ğŸ˜˜',
    messDesc: 'Em Bá» Qua Cho Anh NhÃ©',
    btnAccept: ' 1 CÆ¡ Há»™i Cuá»‘i CÃ¹ng ThÃ´yyyy',
    messLink: 'https://www.facebook.com/cao.haihuu/
}
